# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "COLOR" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"color" VARCHAR NOT NULL);
create unique index "idx_color" on "COLOR" ("color");
create table "USER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"email" VARCHAR NOT NULL,"password" VARCHAR NOT NULL);
create unique index "idx_email" on "USER" ("email");
create table "USER_ROLE" ("userid" BIGINT NOT NULL,"role" VARCHAR NOT NULL);

# --- !Downs

drop table "COLOR";
drop table "USER";
drop table "USER_ROLE";

